# Generated by Django 4.0.5 on 2022-06-10 17:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaCatagory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('catagory_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('pizza_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=100)),
                ('image', models.ImageField(upload_to='pizza')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='main.pizzacatagory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
