# Generated by Django 3.2.7 on 2022-06-12 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='pizza',
            new_name='Pizza',
        ),
    ]
